# src/main/resources/application.yml
okta:
  oauth2:
    issuer: https://dev-5lxfpxxjzz7ikezw.us.auth0.com/
    client-id: mCSPOS44Naw016qy7nVnzvtIKWzOGl9g
    client-secret: dKPQcbSGqAoP7sG86o1gKeFCzVHJQkF98RbaAUQR-vA2RUZ9OoU7r57jxA7tLqVb

# The sample and instructions above for the callback and logout URL configuration use port 3000.
# If you wish to use a different port, change this and be sure your callback and logout URLs are
# configured with the correct port.
server:
  port: 3000